#!/usr/bin/env node
// =============================================================================
// BUILD-TIME CONFIG INJECTION
// =============================================================================
// Generates public/Services/supabaseClient.js and
// public/admin/src/services/supabaseClient.js with Supabase credentials
// baked in from environment variables.
//
// On Vercel  : env vars are set in the dashboard → injected during `npm run build`
// On local   : env vars are loaded from public/user/.env → injected during `npm run dev`
// =============================================================================

const fs = require('fs');
const path = require('path');

// Load .env for local development. On Vercel, env vars are already in process.env.
const envPath = path.join(__dirname, '..', 'public', 'user', '.env');
if (fs.existsSync(envPath)) {
  require('dotenv').config({ path: envPath });
}

const SUPABASE_URL = process.env.SUPABASE_URL || '';
const SUPABASE_ANON_KEY = process.env.SUPABASE_ANON_KEY || '';

if (!SUPABASE_URL || !SUPABASE_ANON_KEY) {
  console.warn('');
  console.warn('⚠️  WARNING: SUPABASE_URL or SUPABASE_ANON_KEY is not set.');
  console.warn('   The generated supabaseClient.js files will have empty values.');
  console.warn('   → Local dev: check public/user/.env');
  console.warn('   → Vercel:    set them in Settings → Environment Variables');
  console.warn('');
}

// ---------------------------------------------------------------------------
// Template — matches the exact structure that works with the existing codebase
// ---------------------------------------------------------------------------
function generateClientJS(sessionLabel) {
  return `// AUTO-GENERATED by scripts/inject-env.js — do not edit manually.
// Regenerate: npm run build  (or npm run dev for local)

import { createClient } from 'https://cdn.jsdelivr.net/npm/@supabase/supabase-js@2.39.0/+esm';

const supabaseUrl = "${SUPABASE_URL}";
const supabaseAnonKey = "${SUPABASE_ANON_KEY}";

if (!supabaseUrl || !supabaseAnonKey || supabaseUrl.includes('YOUR_SUPABASE_URL')) {
    const body = document.querySelector('body');
    if (body) {
        body.innerHTML = \`
            <div style="padding: 2rem; text-align: center; font-family: sans-serif; background-color: #fff5f5; color: #c53030; position: fixed; top: 0; left: 0; right: 0; bottom: 0; z-index: 9999;">
                <h1 style="font-size: 1.5rem; font-weight: bold;">Configuration Error</h1>
                <p>Supabase credentials are not configured. Run <code>npm run build</code> with proper environment variables.</p>
            </div>
        \`;
    }
    throw new Error("Supabase credentials missing! Set SUPABASE_URL and SUPABASE_ANON_KEY env vars, then run: npm run build");
}

// Create and export the Supabase client with session-only storage
export const supabase = createClient(supabaseUrl, supabaseAnonKey, {
  auth: {
    storage: window.sessionStorage,
    autoRefreshToken: true,
    persistSession: true,
    detectSessionInUrl: true
  }
});

// Global auth state listener
supabase.auth.onAuthStateChange((event, session) => {
  if (event === 'SIGNED_OUT' || (event === 'TOKEN_REFRESHED' && !session)) {
    if (!window.location.pathname.includes('/auth/login')) {
      console.log('${sessionLabel} expired — redirecting to login');
      window.location.replace('/auth/login.html');
    }
  }
});
`;
}

// ---------------------------------------------------------------------------
// Write the files
// ---------------------------------------------------------------------------
const targets = [
  {
    file: path.join(__dirname, '..', 'public', 'Services', 'supabaseClient.js'),
    label: 'Session'
  },
  {
    file: path.join(__dirname, '..', 'public', 'admin', 'src', 'services', 'supabaseClient.js'),
    label: 'Admin session'
  }
];

for (const { file, label } of targets) {
  fs.mkdirSync(path.dirname(file), { recursive: true });
  fs.writeFileSync(file, generateClientJS(label), 'utf-8');
  console.log(`  ✅ ${path.relative(path.join(__dirname, '..'), file)}`);
}

console.log('');
console.log(`  🔗 URL : ${SUPABASE_URL || '(not set)'}`);
console.log(`  🔑 Key : ${SUPABASE_ANON_KEY ? '****' + SUPABASE_ANON_KEY.slice(-8) : '(not set)'}`);
console.log('');
